// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";

import {JunoLaunchpad} from "../src/JunoLaunchpad.sol";
import {CurveMath} from "../src/libraries/CurveMath.sol";
import {UniswapV2Graduator} from "../src/graduators/UniswapV2Graduator.sol";
import {IUniswapV2Factory, IUniswapV2Pair} from "../src/interfaces/IUniswapV2.sol";
import {MockWMON, MockStable} from "./mocks/MockUniswapV2.sol";
import {PresetFixtures} from "./fixtures/PresetFixtures.sol";

/// @notice The app builds curves in TypeScript (`lib/juno/curves.ts`); the
/// launchpad validates and prices them in Solidity. This suite takes every
/// preset the app ships, in both quote tokens, exactly as the app builds it
/// (test/fixtures/PresetFixtures.sol, generated by scripts/curve-fixtures.ts)
/// and checks the two sides agree:
///
/// 1. the launchpad's migration threshold, curve supply and migration base
///    equal the TypeScript prediction to the wei;
/// 2. the curve opens and closes at the valuations the builder was asked for;
/// 3. it can be bought out — the last buy partially filled and refunded;
/// 4. it graduates into a real Uniswap v2 pair (v2-core 1.0.1, solc 0.5.16 —
///    the factory Deploy.s.sol puts on testnet) that opens at the curve's top
///    price within 1e-12.
///
/// Each preset runs twice: bought out in one order from the start price, and
/// bought out after an earlier buy left the price mid-range.
contract PresetParityTest is Test {
    uint256 internal constant Q96 = 1 << 96;
    uint256 internal constant WAD = 1e18;
    /// @dev 1e-12 relative, in forge's 1e18-scaled `assertApproxEqRel` units.
    uint256 internal constant TOLERANCE = 1e6;
    /// @dev Uniswap v2 burns this much LP to address(0) on a pair's first mint.
    uint256 internal constant MINIMUM_LIQUIDITY = 1_000;

    JunoLaunchpad internal launchpad;
    UniswapV2Graduator internal graduator;
    IUniswapV2Factory internal factory;
    MockWMON internal wmon;
    MockStable internal usdc;

    address internal owner = makeAddr("owner");
    address internal creator = makeAddr("creator");
    address internal early = makeAddr("early");
    address internal buyer = makeAddr("buyer");

    function setUp() public {
        wmon = new MockWMON();
        usdc = new MockStable();
        factory = IUniswapV2Factory(deployCode("UniswapV2Factory.sol:UniswapV2Factory", abi.encode(owner)));

        vm.startPrank(owner);
        launchpad = new JunoLaunchpad(owner, 2_000);
        graduator = new UniswapV2Graduator(address(launchpad), factory, address(wmon));
        launchpad.setGraduator(graduator);
        launchpad.setQuoteAllowed(address(usdc), true);
        vm.stopPrank();
    }

    /* -------------------------------------------------------------- */
    /* One test per preset and quote                                  */
    /* -------------------------------------------------------------- */

    function test_parity_contentMon() public {
        _parity(0, false);
    }

    function test_parity_contentUsdc() public {
        _parity(1, false);
    }

    function test_parity_thinNameMon() public {
        _parity(2, false);
    }

    function test_parity_thinNameUsdc() public {
        _parity(3, false);
    }

    function test_parity_ipoBookMon() public {
        _parity(4, false);
    }

    function test_parity_ipoBookUsdc() public {
        _parity(5, false);
    }

    function test_parity_tightNavMon() public {
        _parity(6, false);
    }

    function test_parity_tightNavUsdc() public {
        _parity(7, false);
    }

    function test_parity_contentMon_afterEarlyBuy() public {
        _parity(0, true);
    }

    function test_parity_contentUsdc_afterEarlyBuy() public {
        _parity(1, true);
    }

    function test_parity_thinNameMon_afterEarlyBuy() public {
        _parity(2, true);
    }

    function test_parity_thinNameUsdc_afterEarlyBuy() public {
        _parity(3, true);
    }

    function test_parity_ipoBookMon_afterEarlyBuy() public {
        _parity(4, true);
    }

    function test_parity_ipoBookUsdc_afterEarlyBuy() public {
        _parity(5, true);
    }

    function test_parity_tightNavMon_afterEarlyBuy() public {
        _parity(6, true);
    }

    function test_parity_tightNavUsdc_afterEarlyBuy() public {
        _parity(7, true);
    }

    /// @dev Guards the generator: every preset, in both quotes, exactly once.
    function test_fixtures_coverEveryPresetInBothQuotes() public pure {
        assertEq(PresetFixtures.COUNT, 8);
        bool[2][4] memory seen;
        for (uint256 i; i < PresetFixtures.COUNT; ++i) {
            PresetFixtures.Fixture memory f = PresetFixtures.get(i);
            uint256 q = f.quoteDecimals == 18 ? 0 : 1;
            assertTrue(f.quoteDecimals == 18 || f.quoteDecimals == 6, "quote decimals");
            assertFalse(seen[f.params.preset][q], "duplicate fixture");
            seen[f.params.preset][q] = true;
        }
    }

    /* -------------------------------------------------------------- */
    /* The check                                                      */
    /* -------------------------------------------------------------- */

    function _parity(uint256 index, bool earlyBuy) internal {
        PresetFixtures.Fixture memory f = PresetFixtures.get(index);
        JunoLaunchpad.LaunchParams memory lp = f.params;
        lp.quote = f.quoteDecimals == 18 ? address(0) : address(usdc);
        uint160 top = lp.curve[15].sqrtPriceX96;

        vm.prank(creator);
        address token = launchpad.launch(lp, 0, 0);
        JunoLaunchpad.Pool memory p = launchpad.getPool(token);

        // 1. The chain computes exactly what TypeScript predicted.
        assertEq(p.migrationQuoteThreshold, f.threshold, "threshold: TS vs Solidity");
        assertEq(p.baseReserve, f.curveBase, "curveBase: TS vs Solidity");
        assertEq(p.migrationBase, f.migrationBase, "migrationBase: TS vs Solidity");
        assertEq(p.leftover, launchpad.TOTAL_SUPPLY() - f.curveBase - f.migrationBase, "leftover");
        assertEq(p.preset, lp.preset, "preset id");
        // The builder targets 99% of supply for curve + migration; the rest is the rounding buffer.
        assertApproxEqRel(f.curveBase + f.migrationBase, 990_000_000 ether, 1e12, "99% of supply");

        // 2. …and the curve spans the valuations the builder was asked for.
        assertApproxEqRel(
            _fdv(lp.sqrtStartPriceX96, f.quoteDecimals), f.initialMarketCap * WAD, TOLERANCE, "start FDV"
        );
        assertApproxEqRel(_fdv(top, f.quoteDecimals), f.migrationMarketCap * WAD, TOLERANCE, "top FDV");

        // 3. Buy it out. The last order is twice the threshold: it fills what
        // the curve has left and refunds the rest.
        if (earlyBuy) {
            _buy(lp.quote, token, early, f.threshold / 3);
            assertFalse(launchpad.getPool(token).complete, "early buy stays mid-curve");
        }
        uint256 budget = f.threshold * 2;
        uint256 before = _fund(lp.quote, buyer, budget);
        (uint256 baseOut, uint256 paid) = _buy(lp.quote, token, buyer, budget);
        p = launchpad.getPool(token);

        assertTrue(p.complete, "complete");
        assertEq(p.sqrtPriceX96, top, "ends at the top");
        assertLt(paid, budget, "partial fill");
        assertEq(before - _balanceOf(lp.quote, buyer), paid, "unused quote refunded");
        assertEq(IERC20(token).balanceOf(buyer), baseOut);
        // Rounding favours the pool: the curve can hold a wei more than its
        // threshold after a mid-range stop, never less.
        assertGe(p.quoteReserve, f.threshold, "reserve below threshold");
        if (!earlyBuy) {
            assertEq(p.quoteReserve, f.threshold, "one buy from the start pays the threshold exactly");
        }
        assertEq(_balanceOf(lp.quote, address(launchpad)), _owed(p), "solvent before graduation");

        // 4. Graduate into the real v2 pair created at launch.
        uint256 supply = IERC20(token).totalSupply();
        (address venue, uint256 liquidity) = launchpad.graduate(token);
        assertEq(venue, p.venue, "venue");
        assertEq(
            venue, factory.getPair(token, lp.quote == address(0) ? address(wmon) : lp.quote), "factory pair"
        );

        (uint256 baseReserve, uint256 quoteReserve) = _reserves(venue, token);
        assertEq(baseReserve, f.migrationBase, "pair base");
        assertEq(quoteReserve, p.quoteReserve, "pair quote");
        assertEq(IERC20(venue).balanceOf(graduator.LOCK()), liquidity, "LP locked");
        assertEq(IERC20(venue).totalSupply(), liquidity + MINIMUM_LIQUIDITY, "no other LP");
        assertEq(IERC20(token).totalSupply(), supply - p.baseReserve - p.leftover, "dust and buffer burned");
        assertEq(IERC20(token).balanceOf(address(launchpad)), 0, "nothing left behind");
        assertEq(
            _balanceOf(lp.quote, address(launchpad)), p.creatorFees + launchpad.protocolFees(lp.quote), "fees"
        );

        // The pair opens at the curve's top. Pair price / top price is the base
        // the pair's quote buys at the top price over the base the pair holds.
        uint256 baseAtTop = CurveMath.baseForQuoteAt(quoteReserve, top);
        assertApproxEqRel(baseAtTop, baseReserve, TOLERANCE, "opening price vs curve top");
    }

    /* -------------------------------------------------------------- */
    /* Helpers                                                        */
    /* -------------------------------------------------------------- */

    /// @dev Fully diluted value at a sqrt price, in whole quote tokens, WAD-scaled.
    function _fdv(uint160 sqrtPriceX96, uint8 quoteDecimals) internal view returns (uint256) {
        uint256 scaled = launchpad.TOTAL_SUPPLY() * WAD;
        uint256 quoteWei = Math.mulDiv(Math.mulDiv(scaled, sqrtPriceX96, Q96), sqrtPriceX96, Q96);
        return quoteWei / 10 ** quoteDecimals;
    }

    function _fund(address quote, address who, uint256 amount) internal returns (uint256 balance) {
        if (quote == address(0)) {
            vm.deal(who, who.balance + amount);
        } else {
            usdc.mint(who, amount);
            vm.prank(who);
            usdc.approve(address(launchpad), type(uint256).max);
        }
        return _balanceOf(quote, who);
    }

    function _buy(address quote, address token, address who, uint256 amount)
        internal
        returns (uint256 baseOut, uint256 paid)
    {
        if (_balanceOf(quote, who) < amount) _fund(quote, who, amount);
        vm.prank(who);
        return launchpad.buy{value: quote == address(0) ? amount : 0}(token, amount, 0, who, block.timestamp);
    }

    function _balanceOf(address quote, address who) internal view returns (uint256) {
        return quote == address(0) ? who.balance : IERC20(quote).balanceOf(who);
    }

    function _owed(JunoLaunchpad.Pool memory p) internal view returns (uint256) {
        return p.quoteReserve + p.creatorFees + launchpad.protocolFees(p.quote);
    }

    function _reserves(address pair, address token) internal view returns (uint256 base, uint256 quote) {
        (uint112 r0, uint112 r1,) = IUniswapV2Pair(pair).getReserves();
        return
            IUniswapV2Pair(pair).token0() == token ? (uint256(r0), uint256(r1)) : (uint256(r1), uint256(r0));
    }
}
