import { createWalletClient, http, parseEther, type Address, type Hex } from "viem";

import { CallerError, junoError, junoHandler, junoJson, junoOptions, readJson } from "@/lib/juno/api";
import { publicClient } from "@/lib/juno/client";
import { faucetAccount } from "@/lib/juno/faucet";
import { uiToWei, weiToUi } from "@/lib/juno/launchpad";
import { chain, network, rpcEndpoint } from "@/lib/juno/network";
import { explainFailure } from "@/lib/juno/tx";
import { check, clientIp } from "@/lib/rate-limit";
import { requireAddress } from "../_lib/guards";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const OPTIONS = junoOptions;

/** Where a person can get testnet MON when Juno's own faucet cannot help. */
const PUBLIC_FAUCET = "https://faucet.monad.xyz";

/**
 * MON sent per request. Enough for a launch and a handful of small buys —
 * Monad charges for the gas *limit*, and a launch is the one expensive call.
 */
function amountMon(): number {
  const raw = Number(process.env.FAUCET_AMOUNT_MON ?? 0.5);
  return Number.isFinite(raw) && raw > 0 ? raw : 0.5;
}

/**
 * Monad's reserve balance.
 *
 * A transaction that sends value and leaves its sender below 10 MON reverts —
 * and still pays its gas — *unless* the sender sent nothing in the previous
 * three blocks and has never delegated its code (EIP-7702). The faucet key is
 * a plain account and its sends are serialised, so it may spend below the
 * reserve as long as its sends are three blocks apart: when a send would dip
 * into it, the faucet first waits out the spacing rather than send a transfer
 * the chain would revert.
 */
const RESERVE_WEI = parseEther("10");

/**
 * The block the faucet's last transfer landed in, for the spacing above.
 *
 * No initialiser, on purpose. `next build` traces each file by evaluating its
 * top-level declarations; it took `= null` as this binding's only value, then
 * evaluated `lastSentBlock + SETTLE_BLOCKS` below and failed the production
 * build with "Cannot mix BigInt and other types".
 */
let lastSentBlock: bigint | undefined;

/** A plain value transfer. Fixed by the protocol. */
const TRANSFER_GAS = 21_000n;

/**
 * Blocks a freshly funded account must wait before it can send.
 *
 * Monad executes a block after consensus on it, and an account's balance only
 * counts towards what it may spend once the transfer that funded it is a few
 * blocks deep. Answering the moment the receipt lands sent people straight
 * into a "not enough MON" refusal on their first buy.
 */
const SETTLE_BLOCKS = 3n;
/** Blocks are about 300 ms; three of them, with room for a slow one. */
const SETTLE_BUDGET_MS = 4_000;
const SETTLE_POLL_MS = 300;

const RECEIPT_TIMEOUT_MS = 30_000;

/**
 * One send at a time.
 *
 * Two requests racing each other read the same pending nonce, and the second
 * one is refused as a replacement. Serialising in-process costs nothing at a
 * faucet's volume and makes that impossible within an instance.
 */
let queue: Promise<unknown> = Promise.resolve();
function serial<T>(run: () => Promise<T>): Promise<T> {
  const next = queue.then(run, run);
  queue = next.catch(() => undefined);
  return next;
}

function notTestnet(): Response | null {
  return network() === "testnet"
    ? null
    : junoError("The faucet only runs on Monad testnet.", 404);
}

/**
 * The faucet account, or a 503 that says why there is none.
 *
 * The key is generated by the server and sealed in Mongo (`lib/juno/faucet.ts`),
 * so this fails only when Mongo or `JUNO_KEY_SECRET` is missing — an operator
 * problem, and the person on the phone still has the public faucet.
 */
async function loadFaucet() {
  try {
    return { account: await faucetAccount(), error: null };
  } catch (error) {
    console.error("[juno faucet] key unavailable", error);
    return {
      account: null,
      error: junoJson(
        {
          error: `Juno's faucet is not set up on this server. Get testnet MON at ${PUBLIC_FAUCET} instead.`,
          faucetUrl: PUBLIC_FAUCET,
        },
        { status: 503 },
      ),
    };
  }
}

/**
 * Testnet MON for a new wallet.
 *
 * A wallet created on this device starts empty, and every action in Juno —
 * a buy, a launch — costs gas. Without a way to fund it, a first-time user
 * could look at everything and do nothing.
 *
 * Juno's own faucet key (`lib/juno/faucet.ts` — generated by the server,
 * sealed at rest, funded by the operator) answers in a second and does not
 * ask for a captcha. When it is empty or below Monad's reserve, the answer is
 * a readable refusal naming the public faucet and this faucet's address, so
 * the person can go elsewhere and an operator can top it up — never a fake
 * balance.
 *
 * Testnet only: on mainnet this refuses before touching the chain.
 *
 * `GET` → `{ address, balance, amount, symbol }`.
 */
export async function GET() {
  return junoHandler(async () => {
    const refused = notTestnet();
    if (refused) return refused;

    const { account, error } = await loadFaucet();
    if (!account) return error;

    const wei = await publicClient().getBalance({ address: account.address });
    return junoJson({
      address: account.address,
      balance: weiToUi(wei, 18),
      amount: amountMon(),
      symbol: "MON",
    });
  });
}

/** `POST {wallet}` → `{ hash, amount, symbol: "MON" }`. */
export async function POST(request: Request) {
  return junoHandler(async () => {
    const refused = notTestnet();
    if (refused) return refused;

    const body = await readJson<{ wallet?: unknown }>(request);
    const wallet = requireAddress(body.wallet, "wallet");

    // Per wallet and per network address, so one visitor cannot drain it by
    // minting fresh wallets in a loop.
    const ip = clientIp(request.headers);
    for (const [key, limit, windowMs] of [
      [`faucet:${wallet}`, 3, 10 * 60_000],
      [`faucet-ip:${ip}`, 6, 60 * 60_000],
    ] as const) {
      const limited = check(key, limit, windowMs);
      if (!limited.ok) {
        return junoJson(
          {
            error: `Too many faucet requests. Try again in ${Math.ceil(limited.retryAfter / 60)} min.`,
            retryAfter: limited.retryAfter,
          },
          { status: 429, headers: { "Retry-After": String(limited.retryAfter) } },
        );
      }
    }

    const { account, error } = await loadFaucet();
    if (!account) return error;

    const amount = amountMon();
    const value = uiToWei(amount, 18);
    const client = publicClient();

    return serial(async () => {
      const [balance, fees] = await Promise.all([
        client.getBalance({ address: account.address }),
        client.estimateFeesPerGas(),
      ]);

      // What this send costs the faucet.
      const needed = value + TRANSFER_GAS * fees.maxFeePerGas;
      if (balance < needed) {
        return junoJson(
          {
            error:
              balance === 0n
                ? `Juno's faucet is empty. Get testnet MON at ${PUBLIC_FAUCET} with your address; your balance here updates by itself.`
                : `Juno's faucet is running low. Get testnet MON at ${PUBLIC_FAUCET} with your address; your balance here updates by itself.`,
            faucetUrl: PUBLIC_FAUCET,
            // So an operator reading the response knows what to fund.
            faucetAddress: account.address,
            faucetBalance: weiToUi(balance, 18),
          },
          { status: 503 },
        );
      }

      // Below the reserve after this send: only allowed three blocks clear of
      // the last one. Serialised, the previous request already waited, so this
      // is normally instant; a slow head gets a short wait, then a refusal
      // rather than a transfer that would revert.
      if (balance - needed < RESERVE_WEI && lastSentBlock !== undefined) {
        const clearAt = lastSentBlock + SETTLE_BLOCKS;
        const until = Date.now() + SETTLE_BUDGET_MS;
        let head = await client.getBlockNumber({ cacheTime: 0 }).catch(() => null);
        while ((head === null || head < clearAt) && Date.now() < until) {
          await new Promise((resolve) => setTimeout(resolve, SETTLE_POLL_MS));
          head = await client.getBlockNumber({ cacheTime: 0 }).catch(() => null);
        }
        if (head === null || head < clearAt) {
          return junoJson(
            { error: "The faucet is busy — try again in a second.", faucetUrl: PUBLIC_FAUCET },
            { status: 503, headers: { "Retry-After": "1" } },
          );
        }
      }

      const walletClient = createWalletClient({
        account,
        chain: chain(),
        transport: http(rpcEndpoint()),
      });

      let hash: Hex;
      try {
        hash = await walletClient.sendTransaction({
          to: wallet as Address,
          value,
          gas: TRANSFER_GAS,
          maxFeePerGas: fees.maxFeePerGas,
          maxPriorityFeePerGas: fees.maxPriorityFeePerGas,
        });
      } catch (sendError) {
        console.error("[juno faucet] send refused", sendError);
        return junoJson(
          {
            error: `The faucet could not send: ${explainFailure(sendError)}`,
            faucetUrl: PUBLIC_FAUCET,
          },
          { status: 503 },
        );
      }

      let receipt: Awaited<ReturnType<typeof client.waitForTransactionReceipt>>;
      try {
        receipt = await client.waitForTransactionReceipt({ hash, timeout: RECEIPT_TIMEOUT_MS });
      } catch {
        throw new CallerError(
          `The faucet sent ${amount} MON but it has not confirmed yet. It is ${hash}.`,
          504,
        );
      }
      if (receipt.status !== "success") {
        return junoJson(
          {
            error: `The faucet's transfer reverted. It is on-chain as ${hash}. Get testnet MON at ${PUBLIC_FAUCET} instead.`,
            faucetUrl: PUBLIC_FAUCET,
          },
          { status: 503 },
        );
      }

      /*
       * Wait until the funding is spendable.
       *
       * Bounded: if the head is slow to move, answering a moment early is
       * better than holding the request — the worst case is one retry of the
       * person's first transaction, which the app already explains.
       */
      lastSentBlock = receipt.blockNumber;
      const spendableAt = receipt.blockNumber + SETTLE_BLOCKS;
      const deadline = Date.now() + SETTLE_BUDGET_MS;
      while (Date.now() < deadline) {
        const head = await client.getBlockNumber({ cacheTime: 0 }).catch(() => null);
        if (head !== null && head >= spendableAt) break;
        await new Promise((resolve) => setTimeout(resolve, SETTLE_POLL_MS));
      }

      return junoJson({ hash, amount, symbol: "MON" });
    });
  });
}
